
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "750973d69f561999015c4d650eae5ba2ba8bdca1",
 "version": "1.0.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
