
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-03T18:51:52-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "cc6c050ee3325e6957dbf60f74dbe79d78d26a8f",
 "version": "3.22.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
